require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const path = require('path');

const app = express();

// Middleware setup
app.use(bodyParser.json());
app.use(express.static('neelperfume'));

// Serve order.html for all routes
app.get('*', (req, res) => {
    try {
        res.sendFile(path.join(__dirname, 'order.html'));
    } catch (error) {
        console.error('Error serving order.html:', error);
        res.status(500).send('Internal Server Error');
    }
});
// Route for processing payments
app.post('/process_payment', async (req, res) => {
    try {
        // Extract token from the request body
        const { token } = req.body;

        // Check if there are cart items
        const cartItems = req.body.products;
        let amount = cartItems.length > 0 ? calculateTotalAmount(cartItems) : 1000; // $10 in cents if no cart items

        // Create a charge using the Stripe API
        const charge = await stripe.charges.create({
            amount: amount,
            currency: 'usd', // Currency
            source: token.id, // Token ID generated by Stripe.js
            description: 'Payment for order' // Description of the payment
        });

        // Send a JSON response indicating successful payment
        res.json({ success: true, message: 'Payment successful', charge });
    } catch (error) {
        // Handle errors during payment processing
        console.error('Error processing payment:', error);
        res.status(500).json({ error: 'An error occurred while processing payment' });
    }
});

// Function to calculate total amount
function calculateTotalAmount(cartItems) {
    return cartItems.reduce((total, item) => total + (item.price * item.quantity), 0);
}

// Start the server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});